apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-service
  labels:
    app: file-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-service
  template:
    metadata:
      labels:
        app: file-service
    spec:
      containers:
        - name: file-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 50051
            - containerPort: {{.Values.service.healthPort}}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.healthPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.healthPort }}
            initialDelaySeconds: 2
            periodSeconds: 5
          envFrom:
            - configMapRef:
                name: file-service-config
            - secretRef:
                name: file-service-secrets
