apiVersion: v1
kind: Service
metadata:
  name: file-service
spec:
  selector:
    app: file-service
  ports:
    - name: grpc
      port: {{.Values.service.port}}
      targetPort: {{.Values.service.port}}
      protocol: TCP
    - name: http
      port: {{ .Values.service.healthPort }}
      targetPort: {{ .Values.service.healthPort }}