apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audit-service
  template:
    metadata:
      labels:
        app: audit-service
    spec:
      containers:
        - name: audit-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.healthPort }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.healthPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.healthPort }}
            initialDelaySeconds: 2
            periodSeconds: 5
          envFrom:
            - configMapRef:
                name: audit-service-config
            - secretRef:
                name: audit-service-secrets