apiVersion: v1
kind: Service
metadata:
  name: audit-service
spec:
  selector:
    app: audit-service
  ports:
    - name: api
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
    - name: health
      port: {{ .Values.service.healthPort }}
      targetPort: {{ .Values.service.healthPort }}