apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: audit-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Anyr00d/DropZone-deployment.git
    targetRevision: HEAD
    path: helm/audit-service
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
